name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: 'Deploy to NuxtHub'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    env:
      SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      SUPABASE_SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_KEY}}
      SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
      NUXT_HUB_PROJECT_KEY: ${{secrets.NUXT_HUB_PROJECT_KEY}}
      NUXT_HUB_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'preview' }}

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Ensure NuxtHub module is installed
        run: npx nuxthub@latest ensure

      - name: Build application
        run: npm run build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: minhatabela-eghx
